# Generated by Django 5.1.4 on 2025-03-16 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KayakRentalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kayaks', models.PositiveIntegerField(default=28)),
            ],
        ),
        migrations.CreateModel(
            name='KayakRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Czas trwania w godzinach')),
            ],
        ),
        migrations.CreateModel(
            name='KayakReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kayak_quantity', models.PositiveIntegerField(default=1)),
                ('kayak_extra_child', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kayak_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.kayakroute')),
            ],
        ),
    ]
