# Generated by Django 5.1.4 on 2025-03-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_kayakreservation_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayakreservation',
            name='kayak_extra_child',
        ),
        migrations.AddField(
            model_name='kayakreservation',
            name='kayak_extra_child_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
