# Generated by Django 5.1.6 on 2025-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_kayakreservation_kayak_extra_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayakrentalsettings',
            name='total_kayaks',
        ),
        migrations.RemoveField(
            model_name='kayakreservation',
            name='kayak_quantity',
        ),
        migrations.AddField(
            model_name='kayakrentalsettings',
            name='total_kayaks_double',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='kayakrentalsettings',
            name='total_kayaks_single',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kayakrentalsettings',
            name='total_waterproof_bags',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='kayakreservation',
            name='kayak_double_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kayakreservation',
            name='kayak_single_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kayakreservation',
            name='waterproof_bag_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
