# Generated by Django 5.1.6 on 2025-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_kayakrentalsettings_total_kayaks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayakrentalsettings',
            name='price_extra_child',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='kayakrentalsettings',
            name='price_waterproof_bag',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='kayakroute',
            name='price_kayak_double',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='kayakroute',
            name='price_kayak_single',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=6),
        ),
    ]
