# Generated by Django 5.1.6 on 2025-03-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_kayakrentalsettings_price_extra_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayakreservation',
            name='user',
        ),
        migrations.AddField(
            model_name='kayakreservation',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kayakreservation',
            name='phone_number',
            field=models.CharField(default='000-000-000', max_length=15),
        ),
        migrations.AddField(
            model_name='kayakreservation',
            name='user_name',
            field=models.CharField(default='Guest', max_length=255),
        ),
    ]
