# Generated by Django 5.1.6 on 2025-03-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cabin_cabinreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinreservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
