# Generated by Django 5.1.6 on 2025-05-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_blogpost_image_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
