# Generated by Django 5.1.6 on 2025-05-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_blogimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
